name: Deploy Appengine dispatcher in production environment

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'default/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: setup gcloud cli
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY_PRODUCTION }}
        project_id: ${{ secrets.PROJECT_ID_PRODUCTION }}
        export_default_credentials: true
    - name : deploy global dispatch.yaml in production environment
      run: "gcloud app deploy dispatch.yaml --quiet --promote"