name: Deploy default app in production environnement

on:
  push:
    branches: [ main ]
    paths:
    - 'default/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build default app
      working-directory: default
      run: | 
        npm ci
        npm run build --if-present
    - name: setup gcloud cli
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY_PRODUCTION }}
        project_id: ${{ secrets.PROJECT_ID_PRODUCTION }}
        export_default_credentials: true
    - name : deploy default app in production environment
      working-directory: default
      run: "gcloud app deploy app.yaml --quiet --promote"